options:
	name: &f[&eMhTreasure&f]
	mainColour: &7

on join:
	set {justJoined::%player's uuid%} to true
	wait 3 ticks
	while player is online:
		add 30 to {playtime::%player's uuid%::seconds} if {justJoined::%player's uuid%} is not set
		if {playtime::%player's uuid%::seconds} is 60:
			add 1 to {playtime::%player's uuid%::minutes}
			remove 60 from {playtime::%player's uuid%::seconds}
			if {playtime::%player's uuid%::minutes} is 60:
				add 1 to {playtime::%player's uuid%::hours}
				remove 60 from {playtime::%player's uuid%::minutes}
				if {playtime::%player's uuid%::hours} is 24:
					remove 24 from {playtime::%player's uuid%::hours}
					add 1 to {playtime::%player's uuid%::days}
		delete {justJoined::%player's uuid%}
		wait 30 seconds

command /playtime [<player>]:
	trigger:
		if arg-1 is not set:
			send "{@name}{@mainColour} Your Playtime%nl%{@mainColour}&lDAYS: {@mainColour}%{playtime::%player's uuid%::days} ? 0%%nl%{@mainColour}&lHOURS: {@mainColour}%{playtime::%player's uuid%::hours} ? 0%%nl%{@mainColour}&lMINUTES: {@mainColour}%{playtime::%player's uuid%::minutes} ? 0%%nl%{@mainColour}&lSECONDS: {@mainColour}%{playtime::%player's uuid%::seconds} ? 0%"
			stop
		else:
			send "{@name}{@mainColour} %arg-1%{@mainColour}'s Playtime%nl%{@mainColour}&lDAYS: {@mainColour}%{playtime::%arg-1's uuid%::days} ? 0%%nl%{@mainColour}&lHOURS: {@mainColour}%{playtime::%arg-1's uuid%::hours} ? 0%%nl%{@mainColour}&lMINUTES: {@mainColour}%{playtime::%arg-1's uuid%::minutes} ? 0%%nl%{@mainColour}&lSECONDS: {@mainColour}%{playtime::%arg-1's uuid%::seconds} ? 0%"

command /resetplaytime:
	permission: op
	trigger:
		delete {playtime::*}
		send "Reset all playtime."
